---
name: DBIx-Custom-Result
version: 0.0201
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Resultset for DBIx::Custom
license: perl
resources:
  license: ~
requires:
  Object::Simple: 2.0702
build_requires:
  Test::More: 0
provides:
  DBIx::Custom::Result:
    file: lib/DBIx/Custom/Result.pm
    version: 0.0201
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
